name: Test run

on:
  workflow_run:
    workflows: [should run tag]
    types:
      - completed
jobs:
  step-one:
    name: step-one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 1.0.0
      - name: run step one
        run: node index.js
