name: Test run

on:
  workflow_run:
    workflows: [should run tag]
    types:
      - completed
jobs:
  step-one:
    name: 'step one'
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "ehe"
